function stats = createStats(n, maxitr)
    
        base_stats = struct( 'weight', zeros(1,n), ...
                         'numIns', 0, ...
                          'ratio', 0, ...
                         'thresh', 0, ...
                          'model', zeros(3,3), ...
                        'err_all', 0, ...
                      'err_model', zeros(1,n), ...
                 'err_model_mean', 0, ...
                             'dh', 0, ...
                             'dw', 0  );
                     
        stats  = repmat(base_stats, 1, maxitr);

end