function stats = recordStats(w, mu, Err, f2, dh, dw, model)
    
%         if iscolumn(w), w= w'; end
        p = w > 0.5;
        stats = struct(  'weight', w', ...
                         'numIns', nnz(p), ...
                          'ratio', nnz(p)/numel(w)*100, ...
                         'thresh', mu, ...
                          'model', reshape(model,3,3)'/norm(model,'fro'), ...
                        'err_all', Err, ...
                      'err_model', f2, ...
                 'err_model_mean', sum(w.*sqrt(f2))/sum(w), ...
                             'dh', dh, ...
                             'dw', dw  );
    
end